// Auto-generated sample data (real EMR services, 19 Jun 2026) for design mockups.
// Shape matches generate.mjs enrichService output. Read-only showcase data.
window.EMR = {
  "generatedAt": "2026-06-19T16:31:26Z",
  "today": {
    "date": "2026-06-19",
    "toLondon": [
      {
        "serviceUid": "W70753",
        "departureTime": "04:58",
        "arrivalTime": "07:07",
        "actualDepartureTime": "04:58",
        "actualArrivalTime": "07:08",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 1,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8A",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70756",
        "departureTime": "05:30",
        "arrivalTime": "07:39",
        "actualDepartureTime": "05:30",
        "actualArrivalTime": "07:34",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": -4,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8B",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21676",
        "departureTime": "05:56",
        "arrivalTime": "08:08",
        "actualDepartureTime": "05:56",
        "actualArrivalTime": "08:09",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 0,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "6",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70763",
        "departureTime": "06:30",
        "arrivalTime": "08:38",
        "actualDepartureTime": "06:30",
        "actualArrivalTime": "08:39",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 1,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21670",
        "departureTime": "07:00",
        "arrivalTime": "09:09",
        "actualDepartureTime": "07:01",
        "actualArrivalTime": "09:09",
        "departureLatenessMin": 1,
        "arrivalLatenessMin": 0,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21675",
        "departureTime": "07:34",
        "arrivalTime": "09:39",
        "actualDepartureTime": "07:34",
        "actualArrivalTime": "09:40",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 0,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8A",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21667",
        "departureTime": "07:59",
        "arrivalTime": "10:09",
        "actualDepartureTime": "07:59",
        "actualArrivalTime": "10:11",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 2,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70775",
        "departureTime": "08:35",
        "arrivalTime": "10:39",
        "actualDepartureTime": "08:35",
        "actualArrivalTime": "10:38",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 0,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21663",
        "departureTime": "09:00",
        "arrivalTime": "11:09",
        "actualDepartureTime": "09:00",
        "actualArrivalTime": "11:11",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 2,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2A",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70781",
        "departureTime": "09:35",
        "arrivalTime": "11:36",
        "actualDepartureTime": "09:35",
        "actualArrivalTime": "11:55",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 19,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70784",
        "departureTime": "10:00",
        "arrivalTime": "12:09",
        "actualDepartureTime": "10:01",
        "actualArrivalTime": "12:26",
        "departureLatenessMin": 1,
        "arrivalLatenessMin": 17,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21659",
        "departureTime": "10:35",
        "arrivalTime": "12:39",
        "actualDepartureTime": "10:35",
        "actualArrivalTime": "12:40",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 1,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21654",
        "departureTime": "11:00",
        "arrivalTime": "13:07",
        "actualDepartureTime": "11:01",
        "actualArrivalTime": "13:19",
        "departureLatenessMin": 1,
        "arrivalLatenessMin": 12,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70793",
        "departureTime": "11:35",
        "arrivalTime": "13:39",
        "actualDepartureTime": "11:35",
        "actualArrivalTime": "13:39",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 0,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "7",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70796",
        "departureTime": "12:00",
        "arrivalTime": "14:09",
        "actualDepartureTime": "12:00",
        "actualArrivalTime": "14:24",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 15,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2A",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70799",
        "departureTime": "12:35",
        "arrivalTime": "14:39",
        "actualDepartureTime": "12:35",
        "actualArrivalTime": "14:47",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 8,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "7",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70802",
        "departureTime": "13:00",
        "arrivalTime": "15:09",
        "actualDepartureTime": "13:05",
        "actualArrivalTime": "15:27",
        "departureLatenessMin": 5,
        "arrivalLatenessMin": 18,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "5A",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70804",
        "departureTime": "13:35",
        "arrivalTime": "15:39",
        "actualDepartureTime": "13:35",
        "actualArrivalTime": "15:47",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 8,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21655",
        "departureTime": "14:00",
        "arrivalTime": "16:09",
        "actualDepartureTime": "14:00",
        "actualArrivalTime": "16:20",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 10,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70810",
        "departureTime": "14:35",
        "arrivalTime": "16:39",
        "actualDepartureTime": "14:35",
        "actualArrivalTime": "16:53",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 13,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70812",
        "departureTime": "15:00",
        "arrivalTime": "17:09",
        "actualDepartureTime": "15:02",
        "actualArrivalTime": "17:26",
        "departureLatenessMin": 2,
        "arrivalLatenessMin": 17,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21666",
        "departureTime": "15:35",
        "arrivalTime": "17:39",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": true,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit at 125mph | Pathed as Class 810 EMU from here"
      },
      {
        "serviceUid": "W70816",
        "departureTime": "16:00",
        "arrivalTime": "17:22",
        "actualDepartureTime": "16:00",
        "actualArrivalTime": null,
        "departureLatenessMin": 0,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "Kettering",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70818",
        "departureTime": "16:35",
        "arrivalTime": "17:29",
        "actualDepartureTime": "16:40",
        "actualArrivalTime": null,
        "departureLatenessMin": 5,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "Leicester",
        "platform": "8",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70820",
        "departureTime": "17:00",
        "arrivalTime": "17:32",
        "actualDepartureTime": "17:07",
        "actualArrivalTime": null,
        "departureLatenessMin": 7,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "Derby",
        "platform": "2A",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21656",
        "departureTime": "17:32",
        "arrivalTime": "18:08",
        "actualDepartureTime": "17:39",
        "actualArrivalTime": null,
        "departureLatenessMin": 6,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "Derby",
        "platform": "8",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70825",
        "departureTime": "18:00",
        "arrivalTime": "18:31",
        "actualDepartureTime": "18:03",
        "actualArrivalTime": null,
        "departureLatenessMin": 3,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "Derby",
        "platform": "2A",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70826",
        "departureTime": "18:35",
        "arrivalTime": "20:36",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8A",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "W70829",
        "departureTime": "19:00",
        "arrivalTime": "21:08",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8B",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "W70832",
        "departureTime": "19:35",
        "arrivalTime": "21:38",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "7",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "W70834",
        "departureTime": "20:00",
        "arrivalTime": "22:07",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "6",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C21546",
        "departureTime": "21:00",
        "arrivalTime": "23:16",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2A",
        "cancelled": true,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit at 125mph | Pathed as Class 810 EMU from here"
      },
      {
        "serviceUid": "W70752",
        "departureTime": "21:45",
        "arrivalTime": "00:23",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "7",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      }
    ],
    "toSheffield": [
      {
        "serviceUid": "C21774",
        "departureTime": "05:27",
        "arrivalTime": "07:42",
        "actualDepartureTime": "05:27",
        "actualArrivalTime": "07:43",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 1,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70940",
        "departureTime": "05:59",
        "arrivalTime": "08:03",
        "actualDepartureTime": "05:58",
        "actualArrivalTime": "08:03",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 0,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70945",
        "departureTime": "07:02",
        "arrivalTime": "09:06",
        "actualDepartureTime": null,
        "actualArrivalTime": "09:08",
        "departureLatenessMin": null,
        "arrivalLatenessMin": 2,
        "origin": "Derby",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit at 125mph"
      },
      {
        "serviceUid": "W70948",
        "departureTime": "07:30",
        "arrivalTime": "09:42",
        "actualDepartureTime": "07:30",
        "actualArrivalTime": "09:45",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 3,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21769",
        "departureTime": "08:03",
        "arrivalTime": "10:04",
        "actualDepartureTime": "08:02",
        "actualArrivalTime": "10:20",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 16,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21649",
        "departureTime": "08:32",
        "arrivalTime": "10:42",
        "actualDepartureTime": "08:31",
        "actualArrivalTime": "10:49",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 7,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70956",
        "departureTime": "09:02",
        "arrivalTime": "11:05",
        "actualDepartureTime": "09:01",
        "actualArrivalTime": "11:08",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 3,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70958",
        "departureTime": "09:32",
        "arrivalTime": "11:41",
        "actualDepartureTime": "09:32",
        "actualArrivalTime": "11:46",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 4,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70961",
        "departureTime": "10:02",
        "arrivalTime": "12:05",
        "actualDepartureTime": "10:02",
        "actualArrivalTime": "12:10",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 5,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70964",
        "departureTime": "10:32",
        "arrivalTime": "12:44",
        "actualDepartureTime": "10:31",
        "actualArrivalTime": "12:46",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 2,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70967",
        "departureTime": "11:02",
        "arrivalTime": "13:01",
        "actualDepartureTime": "11:02",
        "actualArrivalTime": "13:01",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 0,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21762",
        "departureTime": "11:32",
        "arrivalTime": "13:41",
        "actualDepartureTime": "11:32",
        "actualArrivalTime": "13:50",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 8,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70972",
        "departureTime": "12:02",
        "arrivalTime": "14:04",
        "actualDepartureTime": "12:02",
        "actualArrivalTime": "14:09",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 5,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70975",
        "departureTime": "12:32",
        "arrivalTime": "14:41",
        "actualDepartureTime": "12:31",
        "actualArrivalTime": "14:49",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 8,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21653",
        "departureTime": "13:02",
        "arrivalTime": "15:04",
        "actualDepartureTime": "13:02",
        "actualArrivalTime": "15:25",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 21,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70981",
        "departureTime": "13:32",
        "arrivalTime": "15:44",
        "actualDepartureTime": "13:32",
        "actualArrivalTime": "15:47",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 3,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70984",
        "departureTime": "14:02",
        "arrivalTime": "16:04",
        "actualDepartureTime": "14:02",
        "actualArrivalTime": "16:08",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 3,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70987",
        "departureTime": "14:32",
        "arrivalTime": "16:41",
        "actualDepartureTime": "14:41",
        "actualArrivalTime": "17:02",
        "departureLatenessMin": 9,
        "arrivalLatenessMin": 21,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21763",
        "departureTime": "15:02",
        "arrivalTime": "17:04",
        "actualDepartureTime": "15:12",
        "actualArrivalTime": "17:33",
        "departureLatenessMin": 10,
        "arrivalLatenessMin": 29,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70992",
        "departureTime": "15:31",
        "arrivalTime": "17:43",
        "actualDepartureTime": "15:31",
        "actualArrivalTime": "17:55",
        "departureLatenessMin": 0,
        "arrivalLatenessMin": 12,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70996",
        "departureTime": "16:02",
        "arrivalTime": "17:27",
        "actualDepartureTime": "16:02",
        "actualArrivalTime": null,
        "departureLatenessMin": 0,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Derby",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 10,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70998",
        "departureTime": "16:32",
        "arrivalTime": "18:14",
        "actualDepartureTime": "16:32",
        "actualArrivalTime": null,
        "departureLatenessMin": 0,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Derby",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21781",
        "departureTime": "17:02",
        "arrivalTime": "17:22",
        "actualDepartureTime": "17:02",
        "actualArrivalTime": null,
        "departureLatenessMin": 0,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Luton",
        "platform": "3",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W71004",
        "departureTime": "17:32",
        "arrivalTime": "19:47",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C21758",
        "departureTime": "18:02",
        "arrivalTime": "20:02",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Class 810 EMU at 125mph | Pathed as Diesel multiple unit from here"
      },
      {
        "serviceUid": "W71009",
        "departureTime": "18:32",
        "arrivalTime": "20:47",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C21770",
        "departureTime": "19:02",
        "arrivalTime": "21:18",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "W71013",
        "departureTime": "19:32",
        "arrivalTime": "21:45",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C21761",
        "departureTime": "20:02",
        "arrivalTime": "22:03",
        "actualDepartureTime": null,
        "actualArrivalTime": "22:42",
        "departureLatenessMin": null,
        "arrivalLatenessMin": 39,
        "origin": "Leicester",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "confirmed",
        "stockBranding": "Meridian",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C04182",
        "departureTime": "20:32",
        "arrivalTime": "22:41",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C04184",
        "departureTime": "21:02",
        "arrivalTime": "23:00",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C21760",
        "departureTime": "21:32",
        "arrivalTime": "23:41",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "confirmed",
        "stockBranding": "Aurora",
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21772",
        "departureTime": "22:21",
        "arrivalTime": "00:46",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Starts as Class 810 EMU, changes en route | Pathed as Diesel multiple unit from here"
      }
    ]
  },
  "tomorrow": {
    "date": "2026-06-20",
    "toLondon": [
      {
        "serviceUid": "W70753",
        "departureTime": "04:58",
        "arrivalTime": "07:07",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8A",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70756",
        "departureTime": "05:30",
        "arrivalTime": "07:39",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8B",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21676",
        "departureTime": "05:56",
        "arrivalTime": "08:08",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "6",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70763",
        "departureTime": "06:30",
        "arrivalTime": "08:38",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21670",
        "departureTime": "07:00",
        "arrivalTime": "09:09",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21675",
        "departureTime": "07:34",
        "arrivalTime": "09:39",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8A",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21667",
        "departureTime": "07:59",
        "arrivalTime": "10:09",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70775",
        "departureTime": "08:35",
        "arrivalTime": "10:39",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21663",
        "departureTime": "09:00",
        "arrivalTime": "11:09",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2A",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70781",
        "departureTime": "09:35",
        "arrivalTime": "11:36",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70784",
        "departureTime": "10:00",
        "arrivalTime": "12:09",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21659",
        "departureTime": "10:35",
        "arrivalTime": "12:39",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21654",
        "departureTime": "11:00",
        "arrivalTime": "13:07",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70793",
        "departureTime": "11:35",
        "arrivalTime": "13:39",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "7",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70796",
        "departureTime": "12:00",
        "arrivalTime": "14:09",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2A",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70799",
        "departureTime": "12:35",
        "arrivalTime": "14:39",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "7",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70802",
        "departureTime": "13:00",
        "arrivalTime": "15:09",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "5A",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70804",
        "departureTime": "13:35",
        "arrivalTime": "15:39",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21655",
        "departureTime": "14:00",
        "arrivalTime": "16:09",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70810",
        "departureTime": "14:35",
        "arrivalTime": "16:39",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70812",
        "departureTime": "15:00",
        "arrivalTime": "17:09",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21666",
        "departureTime": "15:35",
        "arrivalTime": "17:39",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8",
        "cancelled": true,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit at 125mph | Pathed as Class 810 EMU from here"
      },
      {
        "serviceUid": "W70816",
        "departureTime": "16:00",
        "arrivalTime": "17:22",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "Kettering",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70818",
        "departureTime": "16:35",
        "arrivalTime": "17:29",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "Leicester",
        "platform": "8",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70820",
        "departureTime": "17:00",
        "arrivalTime": "17:32",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "Derby",
        "platform": "2A",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21656",
        "departureTime": "17:32",
        "arrivalTime": "18:08",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "Derby",
        "platform": "8",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70825",
        "departureTime": "18:00",
        "arrivalTime": "18:31",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "Derby",
        "platform": "2A",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70826",
        "departureTime": "18:35",
        "arrivalTime": "20:36",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8A",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "W70829",
        "departureTime": "19:00",
        "arrivalTime": "21:08",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "8B",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "W70832",
        "departureTime": "19:35",
        "arrivalTime": "21:38",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "7",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "W70834",
        "departureTime": "20:00",
        "arrivalTime": "22:07",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "6",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C21546",
        "departureTime": "21:00",
        "arrivalTime": "23:16",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "2A",
        "cancelled": true,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit at 125mph | Pathed as Class 810 EMU from here"
      },
      {
        "serviceUid": "W70752",
        "departureTime": "21:45",
        "arrivalTime": "00:23",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Sheffield",
        "destination": "St Pancras International",
        "platform": "7",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      }
    ],
    "toSheffield": [
      {
        "serviceUid": "C21774",
        "departureTime": "05:27",
        "arrivalTime": "07:42",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70940",
        "departureTime": "05:59",
        "arrivalTime": "08:03",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70945",
        "departureTime": "07:02",
        "arrivalTime": "09:06",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Derby",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit at 125mph"
      },
      {
        "serviceUid": "W70948",
        "departureTime": "07:30",
        "arrivalTime": "09:42",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21769",
        "departureTime": "08:03",
        "arrivalTime": "10:04",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21649",
        "departureTime": "08:32",
        "arrivalTime": "10:42",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70956",
        "departureTime": "09:02",
        "arrivalTime": "11:05",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70958",
        "departureTime": "09:32",
        "arrivalTime": "11:41",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70961",
        "departureTime": "10:02",
        "arrivalTime": "12:05",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70964",
        "departureTime": "10:32",
        "arrivalTime": "12:44",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70967",
        "departureTime": "11:02",
        "arrivalTime": "13:01",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21762",
        "departureTime": "11:32",
        "arrivalTime": "13:41",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70972",
        "departureTime": "12:02",
        "arrivalTime": "14:04",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70975",
        "departureTime": "12:32",
        "arrivalTime": "14:41",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21653",
        "departureTime": "13:02",
        "arrivalTime": "15:04",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70981",
        "departureTime": "13:32",
        "arrivalTime": "15:44",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70984",
        "departureTime": "14:02",
        "arrivalTime": "16:04",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70987",
        "departureTime": "14:32",
        "arrivalTime": "16:41",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21763",
        "departureTime": "15:02",
        "arrivalTime": "17:04",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70992",
        "departureTime": "15:31",
        "arrivalTime": "17:43",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70996",
        "departureTime": "16:02",
        "arrivalTime": "17:27",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Derby",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 10,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W70998",
        "departureTime": "16:32",
        "arrivalTime": "18:14",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Derby",
        "platform": "2",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21781",
        "departureTime": "17:02",
        "arrivalTime": "17:22",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Luton",
        "platform": "3",
        "cancelled": false,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "W71004",
        "departureTime": "17:32",
        "arrivalTime": "19:47",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C21758",
        "departureTime": "18:02",
        "arrivalTime": "20:02",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Class 810 EMU at 125mph | Pathed as Diesel multiple unit from here"
      },
      {
        "serviceUid": "W71009",
        "departureTime": "18:32",
        "arrivalTime": "20:47",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C21770",
        "departureTime": "19:02",
        "arrivalTime": "21:18",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "W71013",
        "departureTime": "19:32",
        "arrivalTime": "21:45",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C21761",
        "departureTime": "20:02",
        "arrivalTime": "22:03",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "Leicester",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C04182",
        "departureTime": "20:32",
        "arrivalTime": "22:41",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "4",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C04184",
        "departureTime": "21:02",
        "arrivalTime": "23:00",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": true,
        "stockClass": "222",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Pathed as Diesel multiple unit"
      },
      {
        "serviceUid": "C21760",
        "departureTime": "21:32",
        "arrivalTime": "23:41",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "3",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": 5,
        "unitNumber": null,
        "pathedAs": null
      },
      {
        "serviceUid": "C21772",
        "departureTime": "22:21",
        "arrivalTime": "00:46",
        "actualDepartureTime": null,
        "actualArrivalTime": null,
        "departureLatenessMin": null,
        "arrivalLatenessMin": null,
        "origin": "St Pancras International",
        "destination": "Sheffield",
        "platform": "2",
        "cancelled": false,
        "stockClass": "810",
        "confidence": "predicted",
        "stockBranding": null,
        "numberOfVehicles": null,
        "unitNumber": null,
        "pathedAs": "Starts as Class 810 EMU, changes en route | Pathed as Diesel multiple unit from here"
      }
    ]
  }
};
